import { Router } from "express";
import { z } from "zod";
import * as controller from "../controllers/posts.controller.js";
import * as commentController from "../controllers/comments.controller.js";
import { authenticate } from "../middleware/authenticate.js";
import { requirePostOwnershipOrAdmin } from "../middleware/ownership.js";
import { trustedOrigin } from "../middleware/trusted-origin.js";
import { validate } from "../middleware/validate.js";
import { objectId, pagination, noBody } from "../validators/common.schemas.js";
import { postCreateSchema, postUpdateSchema } from "../validators/post.schemas.js";
import { commentSchema } from "../validators/comment.schemas.js";
export const postsRouter = Router();
const idParams = z.object({ id: objectId }).strict();
const postIdParams = z.object({ postId: objectId }).strict();
const slugParams = z.object({ slug: z.string().regex(/^[a-z0-9-]+$/).max(200) }).strict();
const listQuery = pagination.extend({ authorId: objectId.optional() }).strict();
postsRouter.get("/", validate({ query: listQuery }), controller.list);
postsRouter.get("/slug/:slug", validate({ params: slugParams }), controller.bySlug);
postsRouter.get("/:postId/comments", validate({ params: postIdParams, query: pagination }), commentController.list);
postsRouter.post("/:postId/comments", trustedOrigin, authenticate, validate({ params: postIdParams, body: commentSchema }), commentController.create);
postsRouter.get("/:id", validate({ params: idParams }), controller.get);
postsRouter.post("/", trustedOrigin, authenticate, validate({ body: postCreateSchema }), controller.create);
postsRouter.patch("/:id", trustedOrigin, authenticate, validate({ params: idParams, body: postUpdateSchema }), requirePostOwnershipOrAdmin, controller.update);
postsRouter.delete("/:id", trustedOrigin, authenticate, validate({ params: idParams, body: noBody }), requirePostOwnershipOrAdmin, controller.remove);
