import { Router } from "express";
import { z } from "zod";
import * as controller from "../controllers/posts.controller.js";
import * as commentController from "../controllers/comments.controller.js";
import { authenticate, optionalAuthenticate } from "../middleware/authenticate.js";
import { requirePostOwnershipOrAdmin } from "../middleware/ownership.js";
import { trustedOrigin } from "../middleware/trusted-origin.js";
import { validate } from "../middleware/validate.js";
import { objectId, pagination, noBody } from "../validators/common.schemas.js";
import { postCreateSchema, postUpdateSchema } from "../validators/post.schemas.js";
import { commentSchema } from "../validators/comment.schemas.js";
export const postsRouter = Router();
const idParams = z.object({ id: objectId }).strict();
const postIdParams = z.object({ postId: objectId }).strict();
const slugParams = z.object({ slug: z.string().regex(/^[a-z0-9-]+$/).max(200) }).strict();
const listQuery = pagination.extend({ authorId: objectId.optional() }).strict();
const commentsQuery = pagination.extend({ view: z.enum(["flat", "threads"]).default("flat") }).strict();
postsRouter.get("/", optionalAuthenticate, validate({ query: listQuery }), controller.list);
postsRouter.get("/slug/:slug", optionalAuthenticate, validate({ params: slugParams }), controller.bySlug);
postsRouter.get("/:postId/comments", optionalAuthenticate, validate({ params: postIdParams, query: commentsQuery }), commentController.list);
postsRouter.post("/:postId/comments", trustedOrigin, authenticate, validate({ params: postIdParams, body: commentSchema }), commentController.create);
postsRouter.get("/:id", optionalAuthenticate, validate({ params: idParams }), controller.get);
postsRouter.post("/", trustedOrigin, authenticate, validate({ body: postCreateSchema }), controller.create);
postsRouter.patch("/:id", trustedOrigin, authenticate, validate({ params: idParams, body: postUpdateSchema }), requirePostOwnershipOrAdmin, controller.update);
import * as likesController from "../controllers/likes.controller.js";

postsRouter.put("/:id/like", trustedOrigin, authenticate, validate({ params: idParams, body: noBody }), likesController.likePost);
postsRouter.delete("/:id/like", trustedOrigin, authenticate, validate({ params: idParams, body: noBody }), likesController.unlikePost);
postsRouter.delete("/:id", trustedOrigin, authenticate, validate({ params: idParams, body: noBody }), requirePostOwnershipOrAdmin, controller.remove);
